version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Seoul"
    target-branch: "exp"
    reviewers:
      - "jwoo0122"
    commit-message:
      prefix: "[Dependency]"
    labels:
      - "dependency updates"
