const config = {
  repository: {
    name: 'bezier-react',
    iconExtractPath: 'packages/bezier-icons/icons',
    baseBranchName: 'main',
    owner: 'channel-io',
  },
  commit: {
    message: 'feat(bezier-icons): update icons',
    author: {
      name: 'ch-builder',
      email: 'eng@channel.io',
    },
  },
  pr: {
    title: 'feat(bezier-icons): update icons',
    body: 'Please check the changed part!\n---\nThis Pull Request was generated by bezier-figma-plugin.',
    labels: ['feat:icon'],
  },
}

export default config
