name: "Bug report"
description: "Template for bug reporting"
labels: ["bug"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thank you for writing the issue.
        Before you write, please search for the duplicate issue first!
  - type: "input"
    id: "description"
    attributes:
      label: "Summary"
      description: "Please summarize the bug in one line."
      placeholder: |
        Please enter.
    validations:
      required: true
  - type: "textarea"
    id: "step"
    attributes:
      label: "Reproduction process"
      description: |
        Please explain the process of the bug in detail.
      value: |
        1. ...
        2. ...
        3. ...
        4. ...
  - type: "input"
    id: "version"
    attributes:
      label: "Version of bezier-react"
      description: "Please write the version of bezier-react that caused the bug."
      placeholder: "1.0.1"
    validations:
      required: true
  - type: "input"
    id: "browser"
    attributes:
      label: "Browser"
      description: "Please write about the browser where the bug occurred."
      placeholder: "Google Chrome 93"
  - type: "checkboxes"
    id: "operating-system"
    attributes:
      label: "Operating system"
      description: "Please write about the operating system where the bug occurred."
      options:
        - label: "macOS"
        - label: "Windows"
        - label: "Linux"
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additonal Information"
      description: |
        Please enter additional information (such as screenshots) related to bugs.
