name: "Feature request"
description: "Suggest addition of new features (components, etc.) or improvement of existing features"
labels: ["need triage"]
body:
  - type: "markdown"
    attributes:
      value: |
        🙏 Please write the issue title in English!

        Thank you for writing the issue.
        Before you write, please search for the duplicate issue first!
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please summarize the suggestion within 1 to 2 lines."
    validations:
      required: true
  - type: "textarea"
    id: "reason"
    attributes:
      label: "Reasons for suggestion"
      description: |
        Please explain in detail why this feature should be added/improved.
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed solution"
      description: |
        Please write the specific ways to improve the problem. It's even better if you add code snippets.
    validations:
      required: true
  - type: "textarea"
    id: "reference"
    attributes:
      label: "References"
      description: |
        Please write anything(such as an external link) for reference.
