import {
  type BezierComponentProps,
  type LayoutProps,
  type MarginProps,
} from '~/src/types/ComponentProps'
import { TokenPrefix } from '~/src/types/Token'

import {
  cssVar,
  tokenCssVar,
} from './style'

export const splitByBezierComponentProps = <
  Props extends BezierComponentProps,
>({
    as,
    testId,
    style,
    className,
    interpolation,
    ...rest
  }: Props): [BezierComponentProps, Omit<Props, keyof BezierComponentProps>] => [
    {
      as,
      testId,
      style,
      className,
      interpolation,
    },
    rest,
  ]

export const splitByMarginProps = <Props extends MarginProps>({
  m,
  mx,
  my,
  mt,
  mr,
  mb,
  ml,
  ...rest
}: Props): [MarginProps, Omit<Props, keyof MarginProps>] => [
    {
      m,
      mx,
      my,
      mt,
      mr,
      mb,
      ml,
    },
    rest,
  ]

export const splitByLayoutProps = <Props extends LayoutProps>({
  p,
  px,
  py,
  pt,
  pr,
  pb,
  pl,
  width,
  height,
  maxWidth,
  minWidth,
  maxHeight,
  minHeight,
  position,
  inset,
  top,
  right,
  bottom,
  left,
  shrink,
  grow,
  bgColor,
  borderColor,
  borderRadius,
  borderWidth,
  borderTopWidth,
  borderRightWidth,
  borderBottomWidth,
  borderLeftWidth,
  borderStyle,
  elevation,
  zIndex,
  overflow,
  overflowX,
  overflowY,
  ...rest
}: Props): [LayoutProps, Omit<Props, keyof LayoutProps>] => [
    {
      p,
      px,
      py,
      pt,
      pr,
      pb,
      pl,
      width,
      height,
      maxWidth,
      minWidth,
      maxHeight,
      minHeight,
      position,
      inset,
      top,
      right,
      bottom,
      left,
      shrink,
      grow,
      bgColor,
      borderColor,
      borderRadius,
      borderWidth,
      borderTopWidth,
      borderRightWidth,
      borderBottomWidth,
      borderLeftWidth,
      borderStyle,
      elevation,
      zIndex,
      overflow,
      overflowX,
      overflowY,
    },
    rest,
  ]

export const getMarginStyle = <Props extends MarginProps>({
  m,
  mx,
  my,
  mt,
  mr,
  mb,
  ml,
}: Props) => ({
    '--b-margin-all': m,
    '--b-margin-x': mx,
    '--b-margin-y': my,
    '--b-margin-top': mt,
    '--b-margin-right': mr,
    '--b-margin-bottom': mb,
    '--b-margin-left': ml,
  })

export const getLayoutStyle = <Props extends LayoutProps>({
  p,
  px,
  py,
  pt,
  pr,
  pb,
  pl,
  width,
  height,
  maxWidth,
  minWidth,
  maxHeight,
  minHeight,
  position,
  inset,
  top,
  right,
  bottom,
  left,
  shrink,
  grow,
  bgColor,
  borderColor,
  borderRadius,
  borderWidth,
  borderTopWidth,
  borderRightWidth,
  borderBottomWidth,
  borderLeftWidth,
  borderStyle,
  elevation,
  zIndex,
  overflow,
  overflowX,
  overflowY,
}: Props) => ({
    '--b-padding-all': p,
    '--b-padding-x': px,
    '--b-padding-y': py,
    '--b-padding-top': pt,
    '--b-padding-right': pr,
    '--b-padding-bottom': pb,
    '--b-padding-left': pl,
    '--b-width': width,
    '--b-height': height,
    '--b-max-width': maxWidth,
    '--b-min-width': minWidth,
    '--b-max-height': maxHeight,
    '--b-min-height': minHeight,
    '--b-position': position,
    '--b-inset': inset,
    '--b-top': top,
    '--b-right': right,
    '--b-bottom': bottom,
    '--b-left': left,
    '--b-shrink': shrink,
    '--b-grow': grow,
    '--b-bg-color': cssVar(bgColor),
    '--b-border-color': cssVar(borderColor),
    '--b-border-radius': tokenCssVar(borderRadius && `${TokenPrefix.Radius}-${borderRadius}`),
    '--b-border-width': borderWidth,
    '--b-border-top-width': borderTopWidth,
    '--b-border-right-width': borderRightWidth,
    '--b-border-bottom-width': borderBottomWidth,
    '--b-border-left-width': borderLeftWidth,
    '--b-border-style': borderStyle,
    '--b-elevation': tokenCssVar(elevation && `${TokenPrefix.Elevation}-${elevation}`),
    '--b-z-index': tokenCssVar(zIndex && `${TokenPrefix.ZIndex}-${zIndex}`),
    '--b-overflow': overflow,
    '--b-overflow-x': overflowX,
    '--b-overflow-y': overflowY,
  })
