export type {
  DialogProps as DialogPrimitiveProps,
  DialogCloseProps as DialogPrimitiveCloseProps,
  DialogContentProps as DialogPrimitiveContentProps,
  DialogDescriptionProps as DialogPrimitiveDescriptionProps,
  DialogOverlayProps as DialogPrimitiveOverlayProps,
  DialogPortalProps as DialogPrimitivePortalProps,
  DialogTitleProps as DialogPrimitiveTitleProps,
  DialogTriggerProps as DialogPrimitiveTriggerProps,
} from '@radix-ui/react-dialog'
