export {
  DialogPrimitive as AlphaDialogPrimitive,
  DialogPrimitiveClose as AlphaDialogPrimitiveClose,
  DialogPrimitiveContent as AlphaDialogPrimitiveContent,
  DialogPrimitiveDescription as AlphaDialogPrimitiveDescription,
  DialogPrimitiveOverlay as AlphaDialogPrimitiveOverlay,
  DialogPrimitivePortal as AlphaDialogPrimitivePortal,
  DialogPrimitiveTitle as AlphaDialogPrimitiveTitle,
  DialogPrimitiveTrigger as AlphaDialogPrimitiveTrigger,
} from './DialogPrimitive'
export type {
  DialogPrimitiveProps as AlphaDialogPrimitiveProps,
  DialogPrimitiveCloseProps as AlphaDialogPrimitiveCloseProps,
  DialogPrimitiveContentProps as AlphaDialogPrimitiveContentProps,
  DialogPrimitiveDescriptionProps as AlphaDialogPrimitiveDescriptionProps,
  DialogPrimitiveOverlayProps as AlphaDialogPrimitiveOverlayProps,
  DialogPrimitivePortalProps as AlphaDialogPrimitivePortalProps,
  DialogPrimitiveTitleProps as AlphaDialogPrimitiveTitleProps,
  DialogPrimitiveTriggerProps as AlphaDialogPrimitiveTriggerProps,
} from './DialogPrimitive.types'
