enum ActionType {
  SET_SHOW_CONTENT_HEADER = 'SET_SHOW_CONTENT_HEADER',
  SET_SHOW_COVERABLE_HEADER = 'SET_SHOW_COVERABLE_HEADER',
  SET_SHOW_SIDE_PANEL = 'SET_SHOW_SIDE_PANEL',
  SET_SHOW_SIDE_VIEW = 'SET_SHOW_SIDE_VIEW',
  SET_SHOW_NAVIGATION = 'SET_SHOW_NAVIGATION',
  SET_SIDE_WIDTH = 'SET_SIDE_WIDTH',
  ADD_NAV_OPTION = 'ADD_NAV_OPTION',
  REMOVE_NAV_OPTION = 'REMOVE_NAV_OPTION',
  CLEAR_NAV_OPTION = 'CLEAR_NAV_OPTION',
  ADD_COLUMN_REF = 'ADD_COLUMN_REF',
  REMOVE_COLUMN_REF = 'REMOVE_COLUMN_REF',
}

export default ActionType

