enum ActionType {
  SET_SIDE_WIDTH = 'SET_SIDE_WIDTH',
  SET_SHOW_SIDE = 'SET_SHOW_SIDE',
  OPEN_SIDE_VIEW = 'OPEN_SIDE_VIEW',
  CLOSE_SIDE_VIEW = 'CLOSE_SIDE_VIEW',
  SET_SHOW_NAVIGATION = 'SET_SHOW_NAVIGATION',
  ADD_NAV_OPTION = 'ADD_NAV_OPTION',
  REMOVE_NAV_OPTION = 'REMOVE_NAV_OPTION',
  CLEAR_NAV_OPTION = 'CLEAR_NAV_OPTION',
  ADD_COLUMN_REF = 'ADD_COLUMN_REF',
  REMOVE_COLUMN_REF = 'REMOVE_COLUMN_REF',
}

export default ActionType

